// <auto-generated />
namespace TP7.AccesoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ProductosInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductosInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202008270055507_ProductosInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
